### ISSUE TITLE
 No podspec found for `VideodockCapacitorMediaSession

### ISSUE THREAD

**Issue by juanmaldonadodev** [Videodock/capacitor-media-session#1]
Hi, 
After install the plugin on sync iOS we have this error:
[!] No podspec found for `VideodockCapacitorMediaSession` in `../../node_modules/@videodock/capacitor-media-session`

Do you know how to fix it?

**Comment by juanico18** [comment]
I have found the problem. Can you fix it?
At the iOS platform podifle plugin is adding this:
  pod 'VideodockCapacitorMediaSession', :path => '../../node_modules/@videodock/capacitor-media-session'
  
  But at node_modules that VideodockCapacitorMediaSession does not exists.
  I have changed the name of CapacitorMediaSession.podspec by VideodockCapacitorMediaSession.podspec
  Also change line inside the file:
    s.name = 'VideodockCapacitorMediaSession'
    
    Now compile. Although I have not tested it yet.
    
    Thanks
    Can you add a change on the plugin?

**Comment by juanico18** [comment]
I have created a plugin proposal on capacitor community: https://github.com/capacitor-community/proposals/issues/158

**Comment by ChristiaanScheermeijer** [comment]
Hi @juanico18, sorry for not responding! Somehow I didn't get any notifications...

Currently, we've created this plugin only for the purpose of a Capacitor AndroidTV app. To be honest, I've not even installed this plugin on a project with an iOS platform 😅 

I guess we can easily remove the iOS platform, but I'm also interested in your capacitor community proposal.

**Comment by numerized** [comment]
Hi there, 

Would be nice to see this working on iOS capacitor, I really tried absolutely all media controls plugins I could find and forks of them and I couldn't get any of them to work

**Comment by juanico18** [comment]
> Hi @juanico18, sorry for not responding! Somehow I didn't get any notifications...
> 
> Currently, we've created this plugin only for the purpose of a Capacitor AndroidTV app. To be honest, I've not even installed this plugin on a project with an iOS platform 😅
> 
> I guess we can easily remove the iOS platform, but I'm also interested in your capacitor community proposal.

Thanks for the response

**Comment by ChristiaanScheermeijer** [comment]
@numerized 

Is the basic functionality that this plugin provides enough for your use case?

@juanico18 

No problem!

**Comment by numerized** [comment]
@ChristiaanScheermeijer yes it does apparently.
Just need to be able to display artwork on homescreen as long as playpause

**Comment by ChristiaanScheermeijer** [comment]
Hi @numerized, I've started working on this (#2) after the fix but didn't have the time to finish it.
